version: "3.1"
services:
  nginx:
    image:  nginx
    volumes:
      - "./logs/nginx:/var/log/nginx"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./www:/www"
    ports:
        - "8000:8000"

